version: "3.8"

services:
  mysql:
    container_name: mysql_dev
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DEV_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_DEV_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - dev_data:/var/lib/mysql
    networks:
      - dev-network

  springboot:
    container_name: springboot_dev
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mysql
    environment:
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "8080:8080"
    networks:
      - dev-network

volumes:
  dev_data:

networks:
  dev-network:
    driver: bridge